export default [
    {
        'os':'虎牙直播',
        'img':'/static/os/huya_icon.png',
        'url':'https://www.huya.com/download/'
    },
    {
        'os':'斗鱼直播',
        'img':'/static/os/douyu_icon.png',
        'url':'https://www.douyu.com/client'
    },
    {
        'os':'熊猫直播',
        'img':'/static/os/xiongmao_icon.png',
        'url':'https://www.panda.tv/client.html'
    },
    {
        'os':'龙珠直播(app下载)',
        'img':'/static/os/longzhu_icon.png',
        'url':'http://longzhu.com/app/download?from=fiappdownload'
    },
    {
        'os':'全民直播',
        'img':'/static/os/quanmin_icon.png',
        'url':'https://www.quanmin.tv/static/pages/pc.html'
    },
    {
        'os':'企鹅电竞',
        'img':'/static/os/qie_icon.png',
        'url':'http://egame.qq.com/download'
    },
    {
        'os':'企鹅电竞',
        'img':'/static/os/qie_icon.png',
        'url':'http://egame.qq.com/download'
    },
    {
        'os':'触手直播(app下载)',
        'img':'/static/os/chushou_icon.png',
        'url':'https://chushou.tv/download.htm'
    },
    {
        'os':'bilibili直播(b站客户端app下载)',
        'img':'/static/os/bilibili_icon.png',
        'url':'https://app.bilibili.com/'
    },
    {
        'os':'映客直播',
        'img':'/static/os/yingke_icon.png',
        'url':'http://www.inke.cn/'
    }
]