export default [
    {
        'os':'huya',
        'name':'虎牙直播',
        'icon':'/static/os/huya_icon.png',
        'downUrl':'https://www.huya.com/download/',
        'linkUrl':'http://www.huya.com'
    },
    {
        'os':'douyu',
        'name':'斗鱼直播',
        'icon':'/static/os/douyu_icon.png',
        'downUrl':'https://www.douyu.com/client',
        'linkUrl':'https://www.douyu.com'
    },
    {
        'os':'xiongmao',
        'name':'熊猫直播',
        'icon':'/static/os/xiongmao_icon.png',
        'downUrl':'https://www.panda.tv/client.html',
        'linkUrl':'https://www.panda.tv'
    },
    {
        'os':'longzhu',
        'name':'龙珠直播(app下载)',
        'icon':'/static/os/longzhu_icon.png',
        'downUrl':'http://longzhu.com/app/download?from=fiappdownload',
        'linkUrl':'http://www.longzhu.com'
    },
    {
        'os':'quanming',
        'name':'全民直播',
        'icon':'/static/os/quanmin_icon.png',
        'downUrl':'https://www.quanmin.tv/static/pages/pc.html',
        'linkUrl':'https://www.quanmin.tv'
    },
    {
        'os':'qie',
        'name':'企鹅电竞',
        'icon':'/static/os/qie_icon.png',
        'downUrl':'http://egame.qq.com/download',
        'linkUrl':'http://egame.qq.com'
    },
    {
        'os':'chushou',
        'name':'触手直播(app下载)',
        'icon':'/static/os/chushou_icon.png',
        'downUrl':'https://chushou.tv/download.htm',
        'linkUrl':'https://chushou.tv'
    },
    {
        'os':'bzhan',
        'name':'bilibili直播(b站客户端app下载)',
        'icon':'/static/os/bilibili_icon.png',
        'downUrl':'https://app.bilibili.com/',
        'linkUrl':'https://live.bilibili.com/'
    },
    {
        'os':'yingke',
        'name':'映客直播',
        'icon':'/static/os/yingke_icon.png',
        'downUrl':'http://www.inke.cn/',
        'linkUrl':'http://www.inke.cn/index.html'
    }
]